Jakub improve explorer performance 184
Appsilon/mbaza pull request #291
Opened 2022-08-02 14:12 UTC by jchojna

Closes #184 

### Description

### How to test

2022-08-03 15:05 UTC, kamilzyla requested changes
The core of the solution works :+1: :tada: Great job on researching how to approach this! Let's take some time to simplify the mechanism a bit.

In addition to my comments you might want to take a look at [React Virtualization - react-window vs react-virtuoso](https://dev.to/sanamumtaz/react-virtualization-react-window-vs-react-virtuoso-8g). This article contains a nice summary of various packages which can be used for virtualization. Consider whether we could use `react-virtuoso`: it seems that it would do the job easily with just one dependency. Don't worry about it if you figure it would take too much work.

2022-08-04 15:24 UTC, jchojna commented on app/components/ObservationsInspector.scss
> +  width: 750px !important; // overriding specificity would be too complicated
ahhh.. good point! I missed that prop. Fixed!

2022-08-04 15:34 UTC, jchojna commented on app/components/ObservationsInspector.tsx
> +  if (observation === undefined) return false;
Frankly speaking, this line is more a leftover now, I just realized. I needed to handle undefined case for observation at some point, and forgot to refactor it. Right now it seems redundant. I removed that line

2022-08-04 15:35 UTC, jchojna commented on app/components/ObservationsInspector.scss
> +  .drawer-body {
heh.. corrected :)

2022-08-04 15:55 UTC, jchojna commented on app/styles/_variables.scss
> +$t-observation-card: 0.5s;
Agree. Fixed!

2022-08-04 15:59 UTC, jchojna commented on app/components/ObservationsInspector.tsx
> +          <InfiniteLoader
:open_mouth:

2022-08-04 16:17 UTC, jchojna commented on package.json
> +    "react-spinners": "^0.13.4",
Done

2022-08-04 17:07 UTC, jchojna commented on app/components/ObservationsInspector.tsx
> +          <InfiniteLoader
I didn't realize that having just `FixedSizeList` will do the trick here. Fixed!

2022-08-05 08:34 UTC, kamilzyla approved these changes
LGTM, works well! Great job :grin: :100:

2022-08-05 08:53 UTC, merged