Ftr/default language
Appsilon/mbaza pull request #366
Opened 2023-06-02 06:14 UTC by ineelhere

## Change Mbaza App's Default Language to English

### Changes
* imported `useEffect` from react
* used `useEffect` hook to trigger the `i18n.changeLanguage('en')` call when the component mounts

### How to test
* package and run the app on local with codes in this branch
* All text should appear in English by default
* user should be also able to switch to Francias

2023-06-02 10:00 UTC, kamilzyla requested changes

2023-06-02 10:10 UTC, kamilzyla requested changes
Are we sure of this change? French was made the default on an explicit request from Robbie (#199). If we do want to proceed, see my comment in the code :slightly_smiling_face:

2023-06-02 10:23 UTC, ineelhere commented on src/renderer/containers/App.tsx
> +
Wow! This is so cool 😮 In my quest to learn and apply TypeScript, I over-engineered things 😅 
I've updated the PR with the change 🙂

2023-06-02 10:41 UTC, ineelhere commented
> Are we sure of this change? French was made the default on an explicit request from Robbie (#199). If we do want to proceed, see my comment in the code 🙂

@magdakunat @Marundu could you please join @kamilzyla in this thread regarding if we are sure of this change? 🙂 
 
In case we do want to proceed, I have already pushed the changes you've suggested in the review, @kamilzyla 🙂

2023-06-02 10:51 UTC, kamilzyla approved these changes
You have a green light from me on the technical side; feel free to merge once we confirm that we want this change :+1:

2023-06-05 07:03 UTC, Marundu commented
Mbaza is being adopted/ will be adopted by a wider number of users. It makes sense to have the default language as Englihs, since that is more widely spoken than French. This is why I requested for the change.

2023-06-05 13:01 UTC, magdakunat commented
> > Are we sure of this change? French was made the default on an explicit request from Robbie (#199). If we do want to proceed, see my comment in the code 🙂
> 
> @magdakunat @Marundu could you please join @kamilzyla in this thread regarding if we are sure of this change? 🙂
> 
> In case we do want to proceed, I have already pushed the changes you've suggested in the review, @kamilzyla 🙂

This is @Marundu and Andrzej Białaś decision as the D4G leaders

2023-06-15 07:06 UTC, merged